### ISSUE TITLE
ImportError: No module named requests

### ISSUE THREAD

**Issue by rr0ss0rr** [Ronan-cdn/ecobee#1]
Hi .. Just saw your code.  Running this on a Mac with Python 3.7.4 callable from /usr/local/bin/python3 (I made the location change to your script).  
I'm loading the missing packages through pip, but now receive the following...

File "/Users/richard/bin/ecobee", line 25, in <module>
    from StringIO import StringIO

Do you know how to fix this?

Thanks

**Comment by Ronan-cdn** [comment]
Sorry for the slow reply!

I updated the code and issues should be fixed now for python 3 support.
