### ISSUE TITLE
Output json format?

### ISSUE THREAD

**Issue by rr0ss0rr** [Ronan-cdn/ecobee#2]
Hi,  Thanks for the code, I'm using it to control my humidity levels in the winter with great success.  Curious if it's possible to output the data in json format?  Either raw from the Ecobee or your output?  I'd like to check if the humidifier is turned on and it's cumbersome to parse that currently.  I have it set to "manual" but wanted to add code to see if it's "off"

```
  Humidity:                 37 %
  Humidity adjusted:        36 %
    Mode:                   off
      Setpoint (set):       40 %
```

Also, I'm seeing the Ecobee dropping humidity to 30% without my intervention,  my script sees it at the next invocation and sets it back to what it should be.  It seems to be doing this randomly a few times a day.  Have you seen this?

Thanks again
Richard

**Comment by Ronan-cdn** [comment]
Hi Richard,
Can you just pipe the output and grep on "Mode:"? 
>ecobee | grep "Mode:" | grep -ic "off"
Would return 1 when it is off.

You could also use the --dump option to see all the data.

With regards to the setpoint changing, I haven't seen this. I think that it could happen if the mode was set to 'auto' (using ecobee --humidifier-mode auto, or if you enable 'frost control' on the ecobee website.

**Comment by rr0ss0rr** [comment]
Thanks for responding .. I could have ;-) but decided to write my own in bash.  More of a learning experience than anything else.  The humidity change is weird .. definitely in "manual" and not on frost control.   Happened once 5 days ago.  Not a biggie as it gets changed back to what it should be at the next invocation.  Thanks again, if anything, you gave me inspiration to do some coding.

**Comment by Ronan-cdn** [comment]
Great, glad to hear it!
